/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ejb_demo;

import org.junit.Test;

import my.example.AppInitializr;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        AppInitializr classUnderTest = new AppInitializr();
        
    }
}
