/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my.example;

//@ApplicationPath("/*")
public class AppInitializr {
	
//	extends ResourceConfig
	
//	public AppInitializr() {
//		
//		boolean isRecursive = true;
//		String basePackages = "my.example.*";
//		this.packages(isRecursive, basePackages);
//		
//	}

}
